language: python
python:
- '2.7'
- '3.5'
- '3.6'
deploy:
  provider: pypi
  user: api.mailjet
  password:
    secure: gI8oqHszMz4dTfs8g6aKKZgOMN04HK26mPrrsO2iz6gsUB1b7zM8RwLSWCPH2YjmWaAF9Bx5VrQ6YayLHX3svRWUsWDgBGGCcsogKEfIEmMasKMnjGrVJRS5fb0j/r9d4qXaITdoWeRh7/HBdv6u0gAwMV/fyrT6XiiDwWxbYfyLwbJx9IH79Gkyh6Xwq8nkexd5oQDybE0IQ94Q9/6t0CHbmCLrTinR1q0diV/bKK5+zSqiCmatzIq5kMre32iurs4LPZ4QTWJkQqZSh4UzQAJ42hjH8w+YrDxB4kRjOraqDNKHnr06dcOUFK9bJ0/wZU2MJh0II3hrOo2MUphhChcrKQDWuyCPTcZhDUxVBhcy0wWz3RfxXZ442VxHpCrNyNesxmJZZc9AxMfzerQvCIFGeeJCTunUz5I245FNIsnIqDJ5IiM9Ukn/WIfHsqh5fVVejQotfl6YVmlJ+nmxNQnBIXPWlpg4CXJN/TvFTjLsPeWxGZZJKrMGsVmEqHgtH+31pn/ec6frXbx8cDDcoAteEantQWcM3AJj32BL8mA8RpwWONKfFNKFpWyCtoTq+ERbWjv7EvKgudLqX50WPi2uaGFp8Ik6tWAi7hcgNYneyAhOHv7FZJf582n1dTSB0Fv4izphsmJKjIC02EGXYtKcDFA0m1zWLuqLavuFFO0=
  on:
    tags: true
    repo: mailjet/mailjet-apiv3-python
install: pip install -r requirements.txt
script: python test.py
notifications:
  slack:
    secure: Y6dTB+/gVfUn7z84et8HAS8gb21+FJoeDmz9f6Lkc9VUk8fL5lqrsV5cZedEWH1sXzzbN8GN2qOoLDKFa+HpxxA/27urSSVKYxYzqdZQZtVZBRSjVzflDJAUzUk1zfn1SmkhMJZO+EF7SOGLBSqbR2LgIzac6P6lKP6dtI8ZjS++O8VtaPOWPzxb8AuByOO6YR7sl6ZWO3OK30ovEOnAAjeiAC8nD0isjZylzhABQj2AKSelFf0zczMTJBMlB8gIXh+gf+sIG4RZknDb2qnFxstHU8p8FD54KdfkOA4W8UTGBc+5DUx0z8fVIo9JcBwIbbFIlcvZ5LY7atu7baBQO7jURXk7uI/w9gDFoE+NhrqF06NqeCHgySc3KSNf2NaxCiKSD5K4WDxumV16KliMqJzjumwG08+/TqgIzC9/Aj/b+5skxzhWkRP/H5iz8sOqCPHGk1pk7B1PwxuOHwIuzeLQ9aELYQgFIBVMqM2bFLLRk9eRKwpkpagApyAhTjV3hqAmUanL6fiPqIar0f4QQ5vFFronFCp08hVQ/b+WA8cLJ6r3FqBiP0XUzea8gsdbgXO4HB/hXtWx7oWzuPL39kx+aJHdt/rSI90shkk7dzhI3FQy+iSC5QnfVhNPyc3OprzWNlNcZjbI7ElS106LjrKcr8ilAMgpuFa06wuybxo=
