on:
  push:
    branches:
      - main
  pull_request:

name: Commit Checks

jobs:
  # NOTE: Tests also run via `pre-commit`
  pre-commit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        - uses: ./.github/actions/setup-env
          with:
            python-version: "3.11"
        # Executes `pre-commit` with the `make` directive to ensure all dependencies are found
        - run: |
            source $CONDA/bin/activate
            conda activate mailjet
            make pre-commit

#  # linux test suite
#  linux:
#      runs-on: ubuntu-latest
#      name: Test (py${{ matrix.python-version }} on linux-64)
#      strategy:
#        fail-fast: false
#        matrix:
#          python-version: ["3.9", "3.12"]
#      environment: mailjet
#      env:
#         MJ_APIKEY_PUBLIC: '${{ secrets.MJ_APIKEY_PUBLIC }}'
#         MJ_APIKEY_PRIVATE: '${{ secrets.MJ_APIKEY_PRIVATE }}'
#      steps:
#        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
#        - uses: ./.github/actions/setup-env
#          with:
#            python-version: ${{ matrix.python-version }}
#
#        - name: Run tests
#          shell: bash -el {0}
#          run: |
#            conda info
#            conda list
#            make test
#
#
#  macos:
#      runs-on: macos-latest
#      name: Test (py${{ matrix.python-version }} on osx-64)
#      strategy:
#        fail-fast: false
#        matrix:
#          python-version: ["3.9", "3.12"]
#      environment: mailjet
#      env:
#         MJ_APIKEY_PUBLIC: '${{ secrets.MJ_APIKEY_PUBLIC }}'
#         MJ_APIKEY_PRIVATE: '${{ secrets.MJ_APIKEY_PRIVATE }}'
#      steps:
#        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
#        - uses: ./.github/actions/setup-env
#          with:
#            python-version: ${{ matrix.python-version }}
#
#        - name: Run tests
#          shell: sh -l {0}
#          run: |
#            conda info
#            conda list
#            make test

  test:
    name: test py${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [ "3.9", "3.12" ]
    environment: mailjet
    env:
      MJ_APIKEY_PUBLIC: '${{ secrets.MJ_APIKEY_PUBLIC }}'
      MJ_APIKEY_PRIVATE: '${{ secrets.MJ_APIKEY_PRIVATE }}'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: defaults
          show-channel-urls: true
          environment-file: environment.yaml

      - name: Source Scripts
        run: |
          pip install -e .
          conda info
          pytest test.py
