on:
  push:
    branches:
      - main
  pull_request:

name: Commit Checks

jobs:
  # NOTE: Tests also run via `pre-commit`
  pre-commit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        - uses: ./.github/actions/setup-env
          with:
            python-version: "3.11"
        # Executes `pre-commit` with the `make` directive to ensure all dependencies are found
        - run: |
            source $CONDA/bin/activate
            conda activate mailjet
            make pre-commit

  # linux test suite
  linux:
      runs-on: ubuntu-latest
      name: Test (py${{ matrix.python-version }} on linux-64)
      strategy:
        fail-fast: false
        matrix:
          python-version: ["3.9", "3.12"]
      environment: mailjet
      env:
         MJ_APIKEY_PUBLIC: '${{ secrets.MJ_APIKEY_PUBLIC }}'
         MJ_APIKEY_PRIVATE: '${{ secrets.MJ_APIKEY_PRIVATE }}'
      steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        - uses: ./.github/actions/setup-env
          with:
            activate-environment: mailjet
            environment-file: environment.yaml
            auto-update-conda: true
            miniconda-version: "latest"
            python-version: ${{ matrix.python-version }}

        - name: Run tests
          shell: bash -el {0}
          run: |
            conda info
            conda list
            make test


  macos:
      runs-on: macos-latest
      name: Test (py${{ matrix.python-version }} on osx-64)
      strategy:
        fail-fast: false
        matrix:
          python-version: ["3.9", "3.12"]
      environment: mailjet
      env:
         MJ_APIKEY_PUBLIC: '${{ secrets.MJ_APIKEY_PUBLIC }}'
         MJ_APIKEY_PRIVATE: '${{ secrets.MJ_APIKEY_PRIVATE }}'
      steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        - uses: ./.github/actions/setup-env
          with:
            activate-environment: mailjet
            environment-file: environment.yaml
            auto-update-conda: true
            miniconda-version: "latest"
            python-version: ${{ matrix.python-version }}

        - name: Run tests
          shell: sh -l {0}
          run: |
            conda info
            conda list
            make test

  windows:
    runs-on: windows-latest
    name: Test (py${{ matrix.python-version }} on win-64)
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.12" ]
    environment: mailjet
    env:
      MJ_APIKEY_PUBLIC: '${{ secrets.MJ_APIKEY_PUBLIC }}'
      MJ_APIKEY_PRIVATE: '${{ secrets.MJ_APIKEY_PRIVATE }}'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup-env
        with:
          activate-environment: mailjet
          environment-file: environment.yaml
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        shell: cmd /C CALL {0}
        run: >-
          conda info && conda list
          make test
