name: PR Validation

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'

      - name: Build package
        run: |
          pip install --upgrade build setuptools setuptools-scm
          python -m build

      - name: Test installation
        run: |
          pip install dist/*.whl
          python -c "from importlib.metadata import version; print(version('mailjet_rest'))"
