name: Continuous Security Verification

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '37 3 * * 0'

permissions:
  contents: read

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: pip install ruff bandit mypy
      - run: ruff check .
      - run: bandit -c pyproject.toml -r mailjet_rest
      - run: mypy --strict mailjet_rest

  dependency-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with: { python-version: "3.13" }
      - run: python -m pip install --upgrade pip
      - run: pip install pip-audit
      - run: pip-audit --strict

  osv-scanner:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      security-events: write  # For Security Tab
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Run OSV-Scanner
        # zizmor: ignore[unpinned-uses]
        uses: google/osv-scanner-action/osv-scanner-action@6e4298ebc4db23e847df9b2e2de2939d6f066c67
        with:
          scan-args: |
            --recursive
            ./

  semgrep:
    runs-on: ubuntu-latest
    container:
      # Official Semgrep Docker image
      image: semgrep/semgrep@sha256:bdf7013b2c3634a487671158da77c554f531742326b543a9464d2adf6c433ac8
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Run Semgrep CE scan
        run: >-
          semgrep scan
          --config "p/python"
          --config "p/owasp-top-ten"
          --config "p/supply-chain"
          --config "p/command-injection"
          --config "p/insecure-transport"
          --error
