name: Continuous Security Verification

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '37 3 * * 0'

permissions:
  contents: read

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: pip install ruff bandit mypy
      - run: ruff check .
      - run: bandit -c pyproject.toml -r mailjet_rest
      - run: mypy --strict mailjet_rest

  dependency-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"
      - run: pip install pip-audit
      - run: pip install -e .
      # Add --skip mailjet-rest to ignore the local package
      - run: pip-audit --strict --desc --skip mailjet-rest

  osv-scanner:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Run OSV-Scanner
        uses: google/osv-scanner-action/osv-scanner-action@293671231fcf98b1b518df4a450534be5cead007 # v1.9.0
        with:
          scan-args: |-
            -r
            --skip-git
            ./
          format: sarif
          output: results.sarif
      - name: Upload OSV-Scanner SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@babb66d6a26d7f0227163f9202dd34b6b66e5f15 # v4
        with:
          sarif_file: results.sarif

  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:v1.104.0
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Run Semgrep CE scan
        run: >-
          semgrep scan
          --config "p/python"
          --config "p/owasp-top-ten"
          --config "p/supply-chain"
          --config "p/command-injection"
          --config "p/insecure-transport"
          --error
